version: '3'

services:
  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/app
    working_dir: /app
    tty: true
    ports:
      - 3000:3000

  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    tty: true

  db:
    build: ./docker/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
