version: '3'

services:
  back:
    build: ./docker/backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    tty: true
    ports:
      - 8080:8080

  front:
    build: ./docker/frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    tty: true
    ports:
      - 3000:3000

  db:
    build: ./docker/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d

  gui:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db
