GET http://localhost:8080/api/note
###
GET http://localhost:8080/api/note?_id=6227448eb6c177475c40c96c
###
DELETE http://localhost:8080/api/note/delete?_id=6227448eb6c177475c40c96c
###
POST http://localhost:8080/api/note/new
content-type: application/json

{
    "_id": "6227448eb6c177475c40c96c",
    "title": "post_title",
    "body": [
        {
            "text": "post_text1"
        },
        {
            "text": "post_text2"
        },
        {
            "text": "post_text3"
        }
    ]
}

###
PUT http://localhost:8080/api/note/update?_id=6227448eb6c177475c40c96c
content-type: application/json

{
    "title": "update_title",
    "body": [
        {
            "text": "update_text1"
        },
        {
            "text": "update_text2"
        },
        {
            "text": "update_text3"
        }
    ]
}
###
POST http://localhost:8080/api/note/new
content-type: application/json

{
    "title": "new_title",
    "body": [
        {
            "text": "new_text1"
        },
        {
            "text": "new_text2"
        },
        {
            "text": "new_text3"
        }
    ]
}